#!/usr/bin/env python3
"""Test cases for the frosted two-bar UI replayed by tools/patch_ui.py.

Standard library only — no pytest, no dependencies, so this runs anywhere Python does.

    python tests/test_ui_theme.py          # run everything
    python -m unittest discover tests      # same, via unittest

What is being guarded, and why each one is worth a test:

1. The view-id contract (TestLayoutContract)
   MainActivity binds its views with findViewById and casts each one to a specific class.
   A layout that drops an id does NOT fail to compile — it compiles, installs, and dies on
   launch with a NullPointerException. So assets/ui/main.xml has to declare every id in
   patch_ui.REQUIRED_IDS, with the right class, and this is the only thing that checks it.

2. The resource contract (TestResourcesResolve)
   Every @drawable the layout points at is either generated by patch_ui from the theme or
   shipped by upstream. Anything else is a resource that aapt resolves to nothing.

3. The dark-theme leftovers (TestNoWhiteOnFrost)
   The bars changed from black to frosted, so any white text left in the layout is now
   white-on-white and invisible. Only the status badge legitimately keeps white text,
   because it sits on an opaque coloured fill.

4. The top-bar order (TestLayoutContract)
   The reading order across the top bar is a product decision, not an accident: the film or
   style sits centred, its status and then the CS/PE chip follow directly behind it, and the
   group-and-position counter is pinned to the right edge. Nobody would notice if a later
   edit quietly swapped them, so the order is asserted rather than left to whoever edits the
   XML next.

5. Upstream drift (TestAnchorsMatchUpstream)
   patch_ui rewrites Java by matching exact upstream strings. If upstream renames or
   refactors them, the patch silently stops matching and the APK quietly loses its theme.
   This re-checks every anchor against a real checkout when one exists — and skips loudly
   rather than passing when there is no checkout, exactly like tests/run_all.py does.
"""

from __future__ import annotations

import json
import re
import sys
import unittest
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import patch_ui  # noqa: E402  (tools/ on sys.path, imported after the path is set)

NS = "{http://schemas.android.com/apk/res/android}"
# Drawables main.xml may reference that come from upstream rather than from the theme.
UPSTREAM_DRAWABLES = {"badge_ok", "badge_err", "badge_warn"}


def layout_root() -> ET.Element:
    if not patch_ui.UI_LAYOUT.is_file():
        raise AssertionError(f"missing the layout input {patch_ui.UI_LAYOUT}")
    # assets/ui/main.xml is a TEMPLATE: it carries a {ui_package} token that patch_ui
    # fills from the checkout's manifest before writing res/layout/main.xml. Parse the
    # filled all-in-one (base-package) form, which is the XML that actually ships — the
    # raw file is not valid XML on its own because of the token inside the tag name.
    theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
    return ET.fromstring(patch_ui.layout_for(theme, patch_ui.BASE_PACKAGE))


def declared_ids(root: ET.Element) -> dict[str, str]:
    """@+id/name -> simple class name of the element carrying it."""
    out: dict[str, str] = {}
    for el in root.iter():
        ident = el.get(NS + "id")
        if not ident or not ident.startswith("@+id/"):
            continue
        tag = el.tag
        out[ident.split("/", 1)[1]] = tag.rsplit(".", 1)[1] if "." in tag else tag
    return out


def referenced(raw: str, kind: str) -> set[str]:
    return set(re.findall(r"@" + kind + r"/([A-Za-z0-9_]+)", raw))


class TestLayoutContract(unittest.TestCase):
    """assets/ui/main.xml has to keep every view MainActivity binds."""

    def test_every_required_id_is_declared(self):
        ids = declared_ids(layout_root())
        for name in patch_ui.REQUIRED_IDS:
            self.assertIn(name, ids, f"assets/ui/main.xml lost @+id/{name} — "
                                     "MainActivity binds it and would crash on launch")

    def test_required_ids_have_the_class_java_casts_to(self):
        ids = declared_ids(layout_root())
        for name, want in patch_ui.REQUIRED_IDS.items():
            if want is None:
                continue                      # bound to a plain View: any class is fine
            self.assertEqual(ids.get(name), want,
                             f"@+id/{name} is a {ids.get(name)}, but MainActivity casts it "
                             f"to {want} — this is a ClassCastException at startup")

    def test_the_two_bars_are_children_of_panel(self):
        """One panel.setVisibility(GONE) must still hide the whole overlay.

        The layout can change shape freely, but the moment the bars stop being children of
        @id/panel, MainActivity's single-call hide no longer hides them and they hang over
        the brand browser. This is the invariant the split was designed around.
        """
        root = layout_root()
        panels = [el for el in root.iter() if el.get(NS + "id") == "@+id/panel"]
        self.assertEqual(len(panels), 1, "expected exactly one @+id/panel")

        inside = declared_ids(panels[0])
        for name in ("name", "badge", "tag", "count", "meta", "chipscroll", "chips", "hints"):
            self.assertIn(name, inside,
                          f"@+id/{name} moved out of @id/panel — hiding the panel would no "
                          "longer hide it, and it would show through the picker/overlays")

    def test_the_top_bar_reads_name_then_status_then_tag_then_count(self):
        """name (centred) · badge · tag · count (right-aligned) — in that order.

        The film or style is the thing you came to read, so it owns the centre of the bar;
        ACTIVE and the CS/PE chip hang directly off it; 'Kodak 1/20' is reference
        information and belongs at the right edge. Reordering is a one-line XML edit that
        nothing else would catch.
        """
        root = layout_root()
        by_id = {el.get(NS + "id"): el for el in root.iter() if el.get(NS + "id")}
        for name in ("name", "badge", "tag", "count"):
            self.assertIn(f"@+id/{name}", by_id, f"@+id/{name} is gone from the layout")

        head = by_id["@+id/head"]
        head_kids = [el.get(NS + "id") for el in head if el.get(NS + "id")]
        self.assertEqual(["@+id/name", "@+id/badge", "@+id/tag"], head_kids,
                         "the centred group must read name → ACTIVE → CS/PE, in that order")
        self.assertEqual("true", head.get(NS + "layout_centerHorizontal"),
                         "@id/head is no longer centred — the recipe name stops being the "
                         "centre of the bar")

        count = by_id["@+id/count"]
        self.assertEqual("true", count.get(NS + "layout_alignParentRight"),
                         "@id/count is not pinned to the right edge")
        self.assertNotIn("@+id/count", head_kids,
                         "@id/count moved inside @id/head — it would drift with the recipe "
                         "name instead of sitting at the right edge")


class TestResourcesResolve(unittest.TestCase):
    def test_every_drawable_is_generated_or_upstream(self):
        raw = patch_ui.UI_LAYOUT.read_text(encoding="utf-8")
        known = set(patch_ui.GENERATED_DRAWABLES) | UPSTREAM_DRAWABLES
        unknown = referenced(raw, "drawable") - known
        self.assertEqual(set(), unknown,
                         "@drawable references nothing produces — either add it to "
                         "tools/patch_ui.py or to this test's UPSTREAM_DRAWABLES")

    def test_every_id_the_layout_references_is_created_before_it_is_used(self):
        """aapt resolves ids in a single document-order pass, and that is a hard build error.

        This is not theory. assets/ui/main.xml referenced @id/head on the title while the bar
        owning @+id/head was declared further down, so aapt failed with "No resource found
        that matches the given name (at 'layout_toLeftOf' with value '@id/head')" at the very
        first step of the upstream build - a step that aborts R.java generation, before javac
        and before any APK exists. It went unnoticed until the release workflow was finally
        given the patch_ui.py step, because until then nothing had ever compiled this layout:
        the local pipeline had never been run either, and no test here can run aapt (that
        needs the 3 GB NDK r16b toolchain). So the rule aapt enforces is enforced statically
        instead, which costs nothing and catches the whole class.

        A bare @id/x may only appear after @+id/x in the same file. Anything that has to point
        at an id before its declaration must carry the + itself.

        XML comments are blanked out first, keeping their byte offsets so the reported line
        numbers still point into the real file. aapt ignores comments, and this file's own
        comment above the top bar mentions both @+id/head and @id/head while explaining this
        rule — counting those as references made this very test pass on the broken layout.
        """
        raw = patch_ui.UI_LAYOUT.read_text(encoding="utf-8")
        # Same length, so every match keeps its original offset (and therefore its line).
        scan = re.sub(r"<!--.*?-->", lambda m: " " * len(m.group(0)), raw, flags=re.S)
        created: set[str] = set()
        offenders = []
        for m in re.finditer(r"@(\+?)id/([A-Za-z0-9_]+)", scan):
            plus, name = m.group(1), m.group(2)
            line = raw.count("\n", 0, m.start()) + 1
            if plus:
                created.add(name)
            elif name not in created:
                offenders.append("line %d: @id/%s is not created earlier in this file"
                                 % (line, name))
        self.assertEqual([], offenders,
                         "aapt would fail at R.java generation - give the first mention a +: "
                         + "; ".join(offenders))

    def test_every_string_is_one_upstream_defines(self):
        raw = patch_ui.UI_LAYOUT.read_text(encoding="utf-8")
        used = referenced(raw, "string")
        self.assertLessEqual(used, {"app_name"},
                             "the layout references strings that upstream does not define")

    def test_generated_drawables_stay_valid_xml(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        for name, text in patch_ui.drawables_for(theme).items():
            try:
                ET.fromstring(text)
            except ET.ParseError as exc:
                self.fail(f"drawable {name} is not valid XML: {exc}")


class TestNoWhiteOnFrost(unittest.TestCase):
    """The bars went light; white text left behind is now invisible."""

    def test_no_white_text_except_the_badge(self):
        offenders = []
        for el in layout_root().iter():
            colour = (el.get(NS + "textColor") or "").upper().lstrip("#")
            ident = (el.get(NS + "id") or "").split("/")[-1]
            # Only a fully opaque white is a problem; #CC... etc. are secondary inks.
            if len(colour) == 8 and colour.endswith("FFFFFF") and colour.startswith("FF"):
                if ident != "badge":
                    offenders.append(ident or "(no id)")
        self.assertEqual([], offenders,
                         "white text on the frosted bars would be invisible — use the ink "
                         "colours from catalog/ui-theme.json (the badge is exempt: it sits "
                         "on an opaque coloured fill)")


class TestThemeFile(unittest.TestCase):
    def test_every_colour_is_argb_hex_and_parses(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        for key, value in theme.items():
            if isinstance(value, str) and value.startswith("#"):
                patch_ui.java_literal(value)      # raises on anything malformed

    def test_every_drawable_this_writes_is_declared(self):
        """TestResourcesResolve trusts GENERATED_DRAWABLES; keep the two lists in step.

        drawables_for() keys carry the .xml suffix, GENERATED_DRAWABLES carries resource
        names as an @drawable reference spells them.
        """
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        written = {name[: -len(".xml")] for name in patch_ui.drawables_for(theme)}
        self.assertEqual(set(patch_ui.GENERATED_DRAWABLES), written,
                         "tools/patch_ui.py GENERATED_DRAWABLES and drawables_for() disagree "
                         "— TestResourcesResolve would then let a missing resource through")

    def test_constants_replacement_keeps_the_names_java_calls(self):
        """Renaming a constant would break every call site; only values may change."""
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        line = patch_ui.constants_for(theme)
        for name in ("ACCENT", "INK", "WHITE", "DIM"):
            self.assertRegex(line, rf"\b{name} = 0x[0-9A-F]{{8}}", f"{name} vanished")


class TestVisibilityToggles(unittest.TestCase):
    """The layout carries {…} tokens; a bad substitution fails at launch, not at build."""

    def test_layout_is_valid_xml_after_substitution(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        try:
            ET.fromstring(patch_ui.layout_for(theme))
        except ET.ParseError as exc:
            self.fail(f"assets/ui/main.xml is not valid XML once filled in: {exc}")

    def test_no_token_is_left_unfilled(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        filled = patch_ui.layout_for(theme)
        self.assertNotIn("{", filled, "an unfilled {token} would land in the XML verbatim")

    def test_every_token_in_the_layout_has_a_theme_key(self):
        """A token with no mapping is caught by patch_ui's 'no { left' check — but only
        after the theme has been loaded, and the message does not name the stray token.

        {ui_package} is the one allowed exception: it is filled from the checkout's
        AndroidManifest.xml (per brand pack), not from a theme key.
        """
        raw = patch_ui.UI_LAYOUT.read_text(encoding="utf-8")
        tokens = set(re.findall(r"\{([a-z_]+)\}", raw)) - {"ui_package"}
        mapped = {t.strip("{}") for t in patch_ui.LAYOUT_TOKENS}
        self.assertEqual(tokens, mapped,
                         "assets/ui/main.xml and patch_ui.LAYOUT_TOKENS disagree — add the "
                         "missing key to catalog/ui-theme.json and to LAYOUT_TOKENS")

    def test_ui_package_token_is_filled_per_target(self):
        """The custom views must reference the package this APK actually builds as.

        The default (all-in-one) uses the base package; a brand pack uses the renamed one.
        A hardcoded base package here would make every pack's layout point at a class that
        does not exist on the pack's package and crash on launch.
        """
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)

        base = patch_ui.layout_for(theme, patch_ui.BASE_PACKAGE)
        self.assertNotIn(patch_ui.PKG_TOKEN, base, "the package token was not filled")
        self.assertIn("com.hairuoliu.sonysoocrecipes.HintBar", base)
        self.assertIn("com.hairuoliu.sonysoocrecipes.PickerView", base)
        self.assertIn("com.hairuoliu.sonysoocrecipes.PromptView", base)
        try:
            ET.fromstring(base)
        except ET.ParseError as exc:
            self.fail(f"base layout is not valid XML: {exc}")

        leica = patch_ui.layout_for(theme, "com.hairuoliu.sonysoocrecipes.leica")
        self.assertNotIn(patch_ui.PKG_TOKEN, leica, "the package token was not filled")
        self.assertIn("com.hairuoliu.sonysoocrecipes.leica.HintBar", leica)
        self.assertIn("com.hairuoliu.sonysoocrecipes.leica.PickerView", leica)
        self.assertIn("com.hairuoliu.sonysoocrecipes.leica.PromptView", leica)
        self.assertNotIn("com.hairuoliu.sonysoocrecipes.HintBar", leica,
                         "a pack layout still references the all-in-one class")
        try:
            ET.fromstring(leica)
        except ET.ParseError as exc:
            self.fail(f"leica layout is not valid XML: {exc}")

    def test_every_toggle_the_layout_uses_is_actually_in_the_theme(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        for token, key in patch_ui.LAYOUT_TOKENS.items():
            self.assertIn(key, theme,
                          f"the layout carries {token} but catalog/ui-theme.json has no "
                          f"{key!r} — patch_ui would substitute an empty visibility")

    def test_a_misspelled_visibility_is_rejected_here(self):
        """'visble' would compile fine and then crash when the layout inflates.

        This is the whole reason patch_ui validates the toggles instead of trusting
        the JSON: the launch-time error names the inflated view, not the theme key.
        """
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        for key in sorted(patch_ui.LAYOUT_TOKENS.values()):
            with self.assertRaises(SystemExit, msg=f"{key} accepts a misspelled value"):
                patch_ui.layout_for(dict(theme, **{key: "visble"}))


class TestPreviewRenders(unittest.TestCase):
    """tools/preview_ui.py is the only way to see this UI without the camera hardware.

    It is not a gate on the APK, but it is worse than useless if it silently stops
    rendering: the layout gets approved on the strength of a page that no longer reflects
    it. So it builds from the same inputs patch_ui uses, and that is asserted here.
    """

    def setUp(self):
        sys.path.insert(0, str(ROOT / "tools"))
        try:
            import preview_ui  # noqa: PLC0415
        except ImportError as exc:                     # pragma: no cover
            self.skipTest(f"preview_ui is not importable: {exc}")
        self.preview_ui = preview_ui

    def test_the_page_builds_from_the_layout_and_the_theme(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        catalog = json.loads(self.preview_ui.CATALOG.read_text(encoding="utf-8"))
        page = self.preview_ui.build_html(theme, patch_ui.layout_for(theme), catalog, None,
                                          patch_ui.DEFAULT_FORK)
        recipe, group_label, _total, _pos = self.preview_ui.pick(catalog, None)
        self.assertIn(recipe["name"], page,
                      "the preview does not show the recipe it was told to render")
        self.assertIn(group_label, page, "the group-and-position counter is missing")
        # Not 'no brace at all' — the page carries CSS and a script. Only a {token} that
        # substitution should have filled is a failure.
        self.assertIsNone(re.search(r"\{[a-z_]+\}", page),
                          "an unfilled {token} reached the preview page")

    def test_the_badge_keeps_an_opaque_fill(self):
        """ACTIVE is drawn with white text; only an opaque fill makes it readable.

        It is the one element allowed to break the 'no white on frost' rule, and the
        reason is that fill. If the preview ever loses it, the preview is lying.
        """
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        catalog = json.loads(self.preview_ui.CATALOG.read_text(encoding="utf-8"))
        page = self.preview_ui.build_html(theme, patch_ui.layout_for(theme), catalog, None,
                                          patch_ui.DEFAULT_FORK)
        badge = re.search(r'class="badge" style="([^"]*)"', page)
        self.assertIsNotNone(badge, "the preview lost the ACTIVE badge")
        if patch_ui.DEFAULT_FORK.is_dir():
            self.assertIn("background:", badge.group(1),
                          "the ACTIVE badge has no fill — white text on the frost is "
                          "invisible, and the real one is an opaque green slab")


class TestBundledFont(unittest.TestCase):
    """The rounded face has to be bundled, and bundling it has one silent failure mode.

    API 10 has no rounded system font and no android:fontFamily, so the .ttf ships as a
    raw asset. If the packaging step loses its -A flag the file simply is not in the APK,
    createFromAsset throws, the catch swallows it, and the app renders Droid Sans — a
    failure with no error message anywhere. Everything here guards against that silence.
    """

    def test_the_theme_names_two_files_that_are_actually_there(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        names = patch_ui.fonts_for(theme)          # raises on a name with no file
        self.assertEqual(2, len(names))
        for name in names:
            path = patch_ui.FONT_DIR / name
            self.assertTrue(path.is_file(), f"assets/fonts/{name} is missing")
            self.assertTrue(name.endswith(".ttf"), f"{name} is not a .ttf")
            # sfnt magic: 0x00010000 for TrueType outlines, 'OTTO' for CFF. A file that is
            # neither is an HTML error page saved under a .ttf name, which happens more
            # often than it should when a font is fetched by URL.
            self.assertIn(path.read_bytes()[:4], (b"\x00\x01\x00\x00", b"OTTO"),
                          f"assets/fonts/{name} is not a font")

    def test_the_licence_travels_with_the_font(self):
        """The OFL's one condition, and the one failure nothing else here can see.

        NOTICE.md requires the licence obligation to travel with the APK rather than stay
        behind in the repository. A payload that quietly dropped the .txt would still
        build, still look right on the camera, and still pass every other case in this
        class — a missing text file cannot make the app misbehave. So the payload set is
        asserted directly instead of trusting the copy loop to keep including it.
        """
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        payloads = patch_ui.font_payloads(theme)
        for name in patch_ui.fonts_for(theme):
            self.assertIn(name, payloads, f"{name} would not be copied into the checkout")
        licences = [n for n in payloads if n.lower().endswith(".txt")]
        self.assertTrue(licences,
                        "no licence text in the font payload: the OFL requires the licence "
                        "to ship with the font it covers, and NOTICE.md says so explicitly")
        text = payloads[licences[0]].decode("utf-8", "replace").upper()
        self.assertIn("SIL OPEN FONT LICENSE", text,
                      f"{licences[0]} does not read like the OFL")

    def test_a_font_the_theme_invents_is_rejected(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        with self.assertRaises(SystemExit, msg="a missing .ttf must stop the build here, "
                                               "not at launch on the camera"):
            patch_ui.fonts_for(dict(theme, font_bold="NotARealFace.ttf"))

    def test_the_packaging_step_ships_assets(self):
        fork = ROOT / "build" / "recipe-lab-sony-pmca"
        if not (fork / "AndroidManifest.xml").is_file():
            self.skipTest("no upstream checkout — nothing to compare the anchors against")
        for rel, old, new, label in patch_ui.script_edits():
            path = fork / rel
            self.assertTrue(path.is_file(), f"{rel} is gone from the checkout")
            text = path.read_text(encoding="utf-8")
            self.assertTrue(old in text or new in text,
                            f"{rel}: the aapt line moved — {label} must be re-anchored")
        # Upstream keeps build.sh and build.cmd in step by its own rule; a patch that only
        # lands in one of them makes Linux and Windows builds disagree, and CI is Linux.
        flags = [("-A assets" in (fork / rel).read_text(encoding="utf-8"))
                 for rel, _o, _n, _l in patch_ui.script_edits()]
        self.assertTrue(all(flags) or not any(flags),
                        "only one of build.sh / build.cmd carries -A assets")


class TestAnchorsMatchUpstream(unittest.TestCase):
    """Silent drift detector — skipped loudly when there is no checkout to check."""

    def setUp(self):
        self.fork = ROOT / "build" / "recipe-lab-sony-pmca"
        if not (self.fork / "AndroidManifest.xml").is_file():
            self.skipTest("no upstream checkout — nothing to compare the anchors against")

    def test_every_java_anchor_still_resolves(self):
        """Each anchor must still match the upstream line, or already be applied.

        After patch_ui has run, the OLD string is gone and the NEW one is there — both are
        fine. What fails is neither: the pack or upstream moved that code and every future
        build would silently skip the edit, shipping an APK that quietly lost its theme.
        """
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        for fname, old, new, label in patch_ui.anchors(theme):
            text = patch_ui.find_source(self.fork, fname).read_text(encoding="utf-8")
            self.assertTrue(
                old in text or new in text,
                f"{fname}: {label!r} matches neither the upstream line nor the patched one — "
                "upstream moved that code, so update the anchor in tools/patch_ui.py",
            )


class TestPickerBrowser(unittest.TestCase):
    """The FN browser is replayed whole from assets/ui/PickerView.java, like the layout.

    It is upstream code (not patched line-by-line), so the only thing guarding it is this
    test plus the apply step in tools/patch_ui.py: a checkout builds with whatever
    PickerView.java upstream shipped unless the replay writes ours over it. The old panel was
    a black two-column BRAND|recipes browser; the new one is a single white column.
    """

    def test_picker_template_exists(self):
        self.assertTrue(patch_ui.PICKER_TEMPLATE.is_file(),
                        "assets/ui/PickerView.java (the new single-column browser) is missing")

    def test_picker_replaces_the_black_two_column_panel(self):
        raw = patch_ui.PICKER_TEMPLATE.read_text(encoding="utf-8")
        # The old panel was black (0xF0101010) with a left BRAND column; both must be gone.
        self.assertNotIn("0xF0101010", raw, "the picker still paints the old black panel")
        self.assertNotIn('"BRAND"', raw, "the picker still draws the left BRAND column")
        self.assertNotIn("colX", raw, "the picker still splits into a brand column + content")

    def test_picker_is_white_and_single_column(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        text = patch_ui.picker_for(theme, patch_ui.BASE_PACKAGE)
        # White background comes from frost_top_start, not the old black literal.
        self.assertIn(patch_ui.java_literal(theme["frost_top_start"]), text)
        self.assertNotIn("0xF0101010", text)

    def test_picker_fills_the_package_token_per_target(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        base = patch_ui.picker_for(theme, patch_ui.BASE_PACKAGE)
        self.assertNotIn(patch_ui.PKG_TOKEN, base)
        self.assertIn("package com.hairuoliu.sonysoocrecipes;", base)
        leica = patch_ui.picker_for(theme, "com.hairuoliu.sonysoocrecipes.leica")
        self.assertNotIn(patch_ui.PKG_TOKEN, leica)
        self.assertIn("package com.hairuoliu.sonysoocrecipes.leica;", leica)
        self.assertNotIn("com.hairuoliu.sonysoocrecipes.HintBar", leica)

    def test_picker_has_no_unfilled_token(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        for pkg in (patch_ui.BASE_PACKAGE, "com.hairuoliu.sonysoocrecipes.leica"):
            text = patch_ui.picker_for(theme, pkg)
            leftover = [t for t in patch_ui.PICKER_TOKENS if t in text]
            self.assertEqual([], leftover, f"unfilled token(s) {leftover} in the picker for {pkg}")

    def test_picker_braces_balance(self):
        raw = patch_ui.PICKER_TEMPLATE.read_text(encoding="utf-8")
        self.assertEqual(raw.count("{"), raw.count("}"),
                         "PickerView.java has unbalanced braces — it would not compile")

    def test_picker_font_is_bumped_by_two(self):
        """The FN browser font was nudged +2 sizes (see the user's font-bump request).

        PickerView scales every size by the device density d, so the bump is +2 in the
        density-independent part: header 9->11, recipe name 13->15, summary 10->12. This
        locks the decision so a later edit cannot silently shrink it back.
        """
        raw = patch_ui.PICKER_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn("head.setTextSize(11 * d)", raw, "header font should be 11*d (+2)")
        self.assertIn("item.setTextSize(15 * d)", raw, "recipe-name font should be 15*d (+2)")
        self.assertIn("small.setTextSize(12 * d)", raw, "summary font should be 12*d (+2)")
        # the old sizes must be gone from the three paint declarations (the baselines in
        # onDraw still use 13*d etc. as vertical offsets, so only the setTextSize lines)
        self.assertNotIn("head.setTextSize(9 * d)", raw)
        self.assertNotIn("item.setTextSize(13 * d)", raw)
        self.assertNotIn("small.setTextSize(10 * d)", raw)

    def test_picker_text_stays_clear_of_the_tag(self):
        """Long recipe names must not run under the PE/CS tag, and the tag must be centred
        between the name and sub-text lines (see the font-bump feedback).

        The name/sub-text are clipped to the left of the tag column, and the tag rect is
        drawn at y+12d..y+24d (between the name baseline y+13d and sub baseline y+24d),
        not at the old top-aligned y+4d..y+16d.
        """
        raw = patch_ui.PICKER_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn("c.clipRect(x - 4 * d, y, tx - 6 * d, y + rowH)", raw,
                      "recipe text is not clipped clear of the tag column")
        self.assertIn("r.set(tx, y + 12 * d, tx + tw, y + 24 * d)", raw,
                      "the PE/CS tag is not centred between the two text lines")
        self.assertNotIn("y + 4 * d, tx + tw, y + 16 * d", raw,
                         "the tag is still top-aligned with the name line")
        self.assertIn("head.measureText(tag) + 16 * d, 52 * d", raw,
                      "the PE/CS tag must be a wider pill (16d padding, 52d floor), "
                      "not the old tight box")

    def test_the_selection_bar_covers_the_enlarged_text(self):
        """The gold selection bar must actually cover the row's text.

        The +2 font bump made this fail silently: name baseline y+13d (15d font) and
        sub-text baseline y+24d (12d font) put the sub-text descenders at ~y+27d, while the
        bar stopped at y+rowH-5d (== y+25d) — so it cut through the bottom of the text.
        rowH is 30d, hence the bottom must reach at least rowH-2d.
        """
        raw = patch_ui.PICKER_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn("r.set(x - 6 * d, y - 1 * d, xr + 6 * d, y + rowH - 2 * d)", raw,
                      "the selection bar does not extend far enough to cover the sub-text")
        self.assertNotIn("y + rowH - 5 * d", raw,
                         "the selection bar still stops above the sub-text descenders")
        self.assertNotIn("y - 4 * d, xr + 6 * d", raw,
                         "the bar sheets empty gold well above the name glyphs again")

    def test_the_header_has_room_above_its_divider(self):
        """'RECIPES · N' must not sit on top of the divider line below it.

        The baseline is at pad+7d and the divider at top-5d. With top = pad+16d the two were
        only ~2d apart below the descenders, which read as the title sitting on the rule.
        """
        raw = patch_ui.PICKER_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn("float top = pad + 20 * d, bottom = h - pad - 24 * d;", raw,
                      "the header band no longer reserves room above the divider")
        self.assertIn("c.drawLine(pad, top - 5 * d, w - pad, top - 5 * d, rule);", raw,
                      "the divider moved; re-check its clearance from the header baseline")


class TestPreviewPickerRenders(unittest.TestCase):
    """tools/preview_picker.py is the only way to see the FN browser without the camera.

    The browser is Canvas-drawn, so the layout-aware preview_ui cannot reach it; this tool
    mirrors PickerView.onDraw() from the catalog and theme. Like TestPreviewRenders, it is
    not a gate on the APK, but it is useless if it silently stops reflecting the browser.
    """

    def setUp(self):
        sys.path.insert(0, str(ROOT / "tools"))
        try:
            import preview_picker  # noqa: PLC0415
        except ImportError as exc:                     # pragma: no cover
            self.skipTest(f"preview_picker is not importable: {exc}")
        self.preview_picker = preview_picker

    def test_the_page_builds_from_the_catalog_and_theme(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        catalog = json.loads(self.preview_picker.CATALOG.read_text(encoding="utf-8"))
        selected = self.preview_picker.pick_selected(catalog, None)
        page = self.preview_picker.build_html(theme, catalog, 2, selected, "Quicksand")
        self.assertIn("RECIPES", page, "the preview does not show the browser header")
        # both the current and the bumped frame are on the page
        self.assertIn("Current (9 / 13 / 10 sp)", page)
        self.assertIn("After (+2:", page)
        # the window must actually render recipe rows, not a blank panel (the scroll
        # anchor bug drew the selection off-screen and showed nothing)
        self.assertIn("rgba(242,184,92", page,
                      "no selection highlight drawn — the browser window rendered blank")
        self.assertIsNone(re.search(r"\{[a-z_]+\}", page),
                          "an unfilled {token} reached the preview page")

    def test_the_bump_changes_the_rendered_font_size(self):
        """The bumped frame must actually draw larger text than the current one.

        A bump that changed nothing would make the preview a lie; this checks the two
        frames disagree on the rendered name font.
        """
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        catalog = json.loads(self.preview_picker.CATALOG.read_text(encoding="utf-8"))
        selected = self.preview_picker.pick_selected(catalog, None)
        before = self.preview_picker.render_frame(theme, catalog, 0, selected, "Quicksand")
        after = self.preview_picker.render_frame(theme, catalog, 2, selected, "Quicksand")
        self.assertNotEqual(before, after, "the bumped frame is identical to the current one")


if __name__ == "__main__":
    unittest.main(verbosity=2)
