#!/usr/bin/env python3
"""Test cases for the frosted two-bar UI replayed by tools/patch_ui.py.

Standard library only — no pytest, no dependencies, so this runs anywhere Python does.

    python tests/test_ui_theme.py          # run everything
    python -m unittest discover tests      # same, via unittest

What is being guarded, and why each one is worth a test:

1. The view-id contract (TestLayoutContract)
   MainActivity binds its views with findViewById and casts each one to a specific class.
   A layout that drops an id does NOT fail to compile — it compiles, installs, and dies on
   launch with a NullPointerException. So assets/ui/main.xml has to declare every id in
   patch_ui.REQUIRED_IDS, with the right class, and this is the only thing that checks it.

2. The resource contract (TestResourcesResolve)
   Every @drawable the layout points at is either generated by patch_ui from the theme or
   shipped by upstream. Anything else is a resource that aapt resolves to nothing.

3. The dark-theme leftovers (TestNoWhiteOnFrost)
   The bars changed from black to frosted, so any white text left in the layout is now
   white-on-white and invisible. Only the status badge legitimately keeps white text,
   because it sits on an opaque coloured fill.

4. The top-bar order (TestLayoutContract)
   The reading order across the top bar is a product decision, not an accident: the recipe
   name sits centred, its status badge and then the position counter follow directly behind
   it, and that is the whole bar - the left brand and the right edge are both empty. Nobody
   would notice if a later edit quietly swapped them, so the order is asserted rather than
   left to whoever edits the XML next.

5. Upstream drift (TestAnchorsMatchUpstream)
   patch_ui rewrites Java by matching exact upstream strings. If upstream renames or
   refactors them, the patch silently stops matching and the APK quietly loses its theme.
   This re-checks every anchor against a real checkout when one exists — and skips loudly
   rather than passing when there is no checkout, exactly like tests/run_all.py does.
"""

from __future__ import annotations

import json
import re
import sys
import unittest
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import patch_ui  # noqa: E402  (tools/ on sys.path, imported after the path is set)

NS = "{http://schemas.android.com/apk/res/android}"
# Drawables main.xml may reference that come from upstream rather than from the theme.
UPSTREAM_DRAWABLES = {"badge_ok", "badge_err", "badge_warn"}


def layout_root() -> ET.Element:
    if not patch_ui.UI_LAYOUT.is_file():
        raise AssertionError(f"missing the layout input {patch_ui.UI_LAYOUT}")
    # assets/ui/main.xml is a TEMPLATE: it carries a {ui_package} token that patch_ui
    # fills from the checkout's manifest before writing res/layout/main.xml. Parse the
    # filled all-in-one (base-package) form, which is the XML that actually ships — the
    # raw file is not valid XML on its own because of the token inside the tag name.
    theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
    return ET.fromstring(patch_ui.layout_for(theme, patch_ui.BASE_PACKAGE))


def declared_ids(root: ET.Element) -> dict[str, str]:
    """@+id/name -> simple class name of the element carrying it."""
    out: dict[str, str] = {}
    for el in root.iter():
        ident = el.get(NS + "id")
        if not ident or not ident.startswith("@+id/"):
            continue
        tag = el.tag
        out[ident.split("/", 1)[1]] = tag.rsplit(".", 1)[1] if "." in tag else tag
    return out


def referenced(raw: str, kind: str) -> set[str]:
    return set(re.findall(r"@" + kind + r"/([A-Za-z0-9_]+)", raw))


class TestLayoutContract(unittest.TestCase):
    """assets/ui/main.xml has to keep every view MainActivity binds."""

    def test_every_required_id_is_declared(self):
        ids = declared_ids(layout_root())
        for name in patch_ui.REQUIRED_IDS:
            self.assertIn(name, ids, f"assets/ui/main.xml lost @+id/{name} — "
                                     "MainActivity binds it and would crash on launch")

    def test_required_ids_have_the_class_java_casts_to(self):
        ids = declared_ids(layout_root())
        for name, want in patch_ui.REQUIRED_IDS.items():
            if want is None:
                continue                      # bound to a plain View: any class is fine
            self.assertEqual(ids.get(name), want,
                             f"@+id/{name} is a {ids.get(name)}, but MainActivity casts it "
                             f"to {want} — this is a ClassCastException at startup")

    def test_the_two_bars_are_children_of_panel(self):
        """One panel.setVisibility(GONE) must still hide the whole overlay.

        The layout can change shape freely, but the moment the bars stop being children of
        @id/panel, MainActivity's single-call hide no longer hides them and they hang over
        the brand browser. This is the invariant the split was designed around.
        """
        root = layout_root()
        panels = [el for el in root.iter() if el.get(NS + "id") == "@+id/panel"]
        self.assertEqual(len(panels), 1, "expected exactly one @+id/panel")

        inside = declared_ids(panels[0])
        for name in ("name", "badge", "tag", "count", "meta", "chipscroll", "chips", "hints"):
            self.assertIn(name, inside,
                          f"@+id/{name} moved out of @id/panel — hiding the panel would no "
                          "longer hide it, and it would show through the picker/overlays")

    def test_the_top_bar_reads_name_then_status_then_position(self):
        """name (centred) · badge · count · meta — in that order.

        The recipe name is the thing you came to read, so it owns the centre of the bar;
        the brand chip and the position counter ('5 / 11') hang directly off it. The
        parameter summary (@+id/meta) is v0.92's retired bottom-bar line, kept declared
        inside the cluster but hidden by the theme since v0.93 — the bar reads name ·
        brand · position only, and the summary returns by flipping meta_visibility in
        catalog/ui-theme.json without touching Java. Reordering is a one-line XML edit
        that nothing else would catch.
        """
        root = layout_root()
        by_id = {el.get(NS + "id"): el for el in root.iter() if el.get(NS + "id")}
        for name in ("name", "badge", "tag", "count"):
            self.assertIn(f"@+id/{name}", by_id, f"@+id/{name} is gone from the layout")

        head = by_id["@+id/head"]
        head_kids = [el.get(NS + "id") for el in head if el.get(NS + "id")]
        self.assertEqual(["@+id/name", "@+id/badge", "@+id/count", "@+id/meta"], head_kids,
                         "the centred cluster must read name → brand → position → "
                         "summary, in order")

        # v0.93: the summary is OFF by default — off in the theme AND wired to the theme
        # token, not hard-coded in the XML (so it stays a one-line theme flip).
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        self.assertEqual("gone", theme.get("meta_visibility"),
                         "the parameter summary is visible again — the v0.93 bar carries "
                         "name · brand · position only")
        meta = by_id["@+id/meta"]
        # layout_root() parses the FILLED layout, so the token is already substituted —
        # what this asserts is that the shipped visibility is the THEME'S decision (a
        # hard-coded 'gone' here would survive a theme flip and lie about the toggle).
        self.assertEqual(theme["meta_visibility"], meta.get(NS + "visibility"),
                         "@+id/meta's visibility does not follow meta_visibility — it is "
                         "hard-coded in the XML instead of wired to the theme token")

        self.assertEqual("true", head.get(NS + "layout_centerHorizontal"),
                         "@id/head is no longer centred — the recipe name stops being the "
                         "centre of the bar")

        # The position counter now lives inside @id/head (it was pinned to the right edge
        # before the centred-cluster redesign); it must NOT also be a right-aligned sibling.
        count = by_id["@+id/count"]
        self.assertNotEqual("true", count.get(NS + "layout_alignParentRight"),
                            "@id/count is still pinned to the right edge — it belongs in the "
                            "centred cluster now")
        self.assertIn("@+id/count", head_kids,
                      "@id/count is not in the centred cluster")

    def test_the_pill_hugs_the_text_vertically(self):
        """v0.93 hardware report: the pill was still twice the text's height.

        Two sources of dead vertical space, both now pinned here. The bar's own vertical
        padding must be 0 (horizontal padding stays), and the TextViews must drop the
        font's reserved leading — Noto Sans SC's line box is ~1.5em, so 18sp text carried
        ~9dp of invisible leading per edge and the capsule read as inflated even at 0dp
        padding. includeFontPadding=false plus a small negative line spacing on the name
        (the tallest child, so the one that sets the bar's height) is as tight as a
        TextView goes; if the hardware ever wants tighter than this, the bar has to move
        to a Canvas-drawn view, not more padding arithmetic.
        """
        root = layout_root()
        by_id = {el.get(NS + "id"): el for el in root.iter() if el.get(NS + "id")}
        topbar = by_id["@+id/topbar"]
        self.assertEqual("0dp", topbar.get(NS + "paddingTop"),
                         "the pill regained top padding — the bar must hug the text")
        self.assertEqual("0dp", topbar.get(NS + "paddingBottom"),
                         "the pill regained bottom padding — the bar must hug the text")

        name = by_id["@+id/name"]
        self.assertEqual("false", name.get(NS + "includeFontPadding"),
                         "the name carries the font's reserved leading again — that "
                         "leading is most of the pill's visual thickness")
        self.assertIsNotNone(name.get(NS + "lineSpacingExtra"),
                             "the name lost its negative line spacing — the line box is "
                             "half of what makes the pill tall")
        badge = by_id["@+id/badge"]
        self.assertEqual("0dp", badge.get(NS + "paddingTop"),
                         "the badge's chip grew its own vertical padding back")
        self.assertEqual("false", badge.get(NS + "includeFontPadding"),
                         "the badge carries font padding — its chip inflates the cluster")


class TestResourcesResolve(unittest.TestCase):
    def test_every_drawable_is_generated_or_upstream(self):
        raw = patch_ui.UI_LAYOUT.read_text(encoding="utf-8")
        known = set(patch_ui.GENERATED_DRAWABLES) | UPSTREAM_DRAWABLES
        unknown = referenced(raw, "drawable") - known
        self.assertEqual(set(), unknown,
                         "@drawable references nothing produces — either add it to "
                         "tools/patch_ui.py or to this test's UPSTREAM_DRAWABLES")

    def test_every_id_the_layout_references_is_created_before_it_is_used(self):
        """aapt resolves ids in a single document-order pass, and that is a hard build error.

        This is not theory. assets/ui/main.xml referenced @id/head on the title while the bar
        owning @+id/head was declared further down, so aapt failed with "No resource found
        that matches the given name (at 'layout_toLeftOf' with value '@id/head')" at the very
        first step of the upstream build - a step that aborts R.java generation, before javac
        and before any APK exists. It went unnoticed until the release workflow was finally
        given the patch_ui.py step, because until then nothing had ever compiled this layout:
        the local pipeline had never been run either, and no test here can run aapt (that
        needs the 3 GB NDK r16b toolchain). So the rule aapt enforces is enforced statically
        instead, which costs nothing and catches the whole class.

        A bare @id/x may only appear after @+id/x in the same file. Anything that has to point
        at an id before its declaration must carry the + itself.

        XML comments are blanked out first, keeping their byte offsets so the reported line
        numbers still point into the real file. aapt ignores comments, and this file's own
        comment above the top bar mentions both @+id/head and @id/head while explaining this
        rule — counting those as references made this very test pass on the broken layout.
        """
        raw = patch_ui.UI_LAYOUT.read_text(encoding="utf-8")
        # Same length, so every match keeps its original offset (and therefore its line).
        scan = re.sub(r"<!--.*?-->", lambda m: " " * len(m.group(0)), raw, flags=re.S)
        created: set[str] = set()
        offenders = []
        for m in re.finditer(r"@(\+?)id/([A-Za-z0-9_]+)", scan):
            plus, name = m.group(1), m.group(2)
            line = raw.count("\n", 0, m.start()) + 1
            if plus:
                created.add(name)
            elif name not in created:
                offenders.append("line %d: @id/%s is not created earlier in this file"
                                 % (line, name))
        self.assertEqual([], offenders,
                         "aapt would fail at R.java generation - give the first mention a +: "
                         + "; ".join(offenders))

    def test_every_string_is_one_upstream_defines(self):
        raw = patch_ui.UI_LAYOUT.read_text(encoding="utf-8")
        used = referenced(raw, "string")
        self.assertLessEqual(used, {"app_name"},
                             "the layout references strings that upstream does not define")

    def test_generated_drawables_stay_valid_xml(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        for name, text in patch_ui.drawables_for(theme).items():
            try:
                ET.fromstring(text)
            except ET.ParseError as exc:
                self.fail(f"drawable {name} is not valid XML: {exc}")


class TestNoWhiteOnFrost(unittest.TestCase):
    """The bars went light; white text left behind is now invisible."""

    def test_no_white_text_except_the_badge(self):
        offenders = []
        for el in layout_root().iter():
            colour = (el.get(NS + "textColor") or "").upper().lstrip("#")
            ident = (el.get(NS + "id") or "").split("/")[-1]
            # Only a fully opaque white is a problem; #CC... etc. are secondary inks.
            if len(colour) == 8 and colour.endswith("FFFFFF") and colour.startswith("FF"):
                if ident != "badge":
                    offenders.append(ident or "(no id)")
        self.assertEqual([], offenders,
                         "white text on the frosted bars would be invisible — use the ink "
                         "colours from catalog/ui-theme.json (the badge is exempt: it sits "
                         "on an opaque coloured fill)")


class TestThemeFile(unittest.TestCase):
    def test_every_colour_is_argb_hex_and_parses(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        for key, value in theme.items():
            if isinstance(value, str) and value.startswith("#"):
                patch_ui.java_literal(value)      # raises on anything malformed

    def test_every_drawable_this_writes_is_declared(self):
        """TestResourcesResolve trusts GENERATED_DRAWABLES; keep the two lists in step.

        drawables_for() keys carry the .xml suffix, GENERATED_DRAWABLES carries resource
        names as an @drawable reference spells them.
        """
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        written = {name[: -len(".xml")] for name in patch_ui.drawables_for(theme)}
        self.assertEqual(set(patch_ui.GENERATED_DRAWABLES), written,
                         "tools/patch_ui.py GENERATED_DRAWABLES and drawables_for() disagree "
                         "— TestResourcesResolve would then let a missing resource through")

    def test_constants_replacement_keeps_the_names_java_calls(self):
        """Renaming a constant would break every call site; only values may change."""
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        line = patch_ui.constants_for(theme)
        for name in ("ACCENT", "INK", "WHITE", "DIM"):
            self.assertRegex(line, rf"\b{name} = 0x[0-9A-F]{{8}}", f"{name} vanished")


class TestVisibilityToggles(unittest.TestCase):
    """The layout carries {…} tokens; a bad substitution fails at launch, not at build."""

    def test_layout_is_valid_xml_after_substitution(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        try:
            ET.fromstring(patch_ui.layout_for(theme))
        except ET.ParseError as exc:
            self.fail(f"assets/ui/main.xml is not valid XML once filled in: {exc}")

    def test_no_token_is_left_unfilled(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        filled = patch_ui.layout_for(theme)
        self.assertNotIn("{", filled, "an unfilled {token} would land in the XML verbatim")

    def test_every_token_in_the_layout_has_a_theme_key(self):
        """A token with no mapping is caught by patch_ui's 'no { left' check — but only
        after the theme has been loaded, and the message does not name the stray token.

        {ui_package} is the one allowed exception: it is filled from the checkout's
        AndroidManifest.xml (per brand pack), not from a theme key.
        """
        raw = patch_ui.UI_LAYOUT.read_text(encoding="utf-8")
        tokens = set(re.findall(r"\{([a-z_]+)\}", raw)) - {"ui_package"}
        mapped = {t.strip("{}") for t in patch_ui.LAYOUT_TOKENS}
        self.assertEqual(tokens, mapped,
                         "assets/ui/main.xml and patch_ui.LAYOUT_TOKENS disagree — add the "
                         "missing key to catalog/ui-theme.json and to LAYOUT_TOKENS")

    def test_ui_package_token_is_filled_per_target(self):
        """The custom views must reference the package this APK actually builds as.

        The default (all-in-one) uses the base package; a brand pack uses the renamed one.
        A hardcoded base package here would make every pack's layout point at a class that
        does not exist on the pack's package and crash on launch.
        """
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)

        base = patch_ui.layout_for(theme, patch_ui.BASE_PACKAGE)
        self.assertNotIn(patch_ui.PKG_TOKEN, base, "the package token was not filled")
        self.assertIn("com.hairuoliu.sonysoocrecipes.HintBar", base)
        self.assertIn("com.hairuoliu.sonysoocrecipes.PickerView", base)
        self.assertIn("com.hairuoliu.sonysoocrecipes.PromptView", base)
        try:
            ET.fromstring(base)
        except ET.ParseError as exc:
            self.fail(f"base layout is not valid XML: {exc}")

        leica = patch_ui.layout_for(theme, "com.hairuoliu.sonysoocrecipes.leica")
        self.assertNotIn(patch_ui.PKG_TOKEN, leica, "the package token was not filled")
        self.assertIn("com.hairuoliu.sonysoocrecipes.leica.HintBar", leica)
        self.assertIn("com.hairuoliu.sonysoocrecipes.leica.PickerView", leica)
        self.assertIn("com.hairuoliu.sonysoocrecipes.leica.PromptView", leica)
        self.assertNotIn("com.hairuoliu.sonysoocrecipes.HintBar", leica,
                         "a pack layout still references the all-in-one class")
        try:
            ET.fromstring(leica)
        except ET.ParseError as exc:
            self.fail(f"leica layout is not valid XML: {exc}")

    def test_every_toggle_the_layout_uses_is_actually_in_the_theme(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        for token, key in patch_ui.LAYOUT_TOKENS.items():
            self.assertIn(key, theme,
                          f"the layout carries {token} but catalog/ui-theme.json has no "
                          f"{key!r} — patch_ui would substitute an empty visibility")

    def test_a_misspelled_visibility_is_rejected_here(self):
        """'visble' would compile fine and then crash when the layout inflates.

        This is the whole reason patch_ui validates the toggles instead of trusting
        the JSON: the launch-time error names the inflated view, not the theme key.
        """
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        for key in sorted(patch_ui.LAYOUT_TOKENS.values()):
            with self.assertRaises(SystemExit, msg=f"{key} accepts a misspelled value"):
                patch_ui.layout_for(dict(theme, **{key: "visble"}))


class TestPreviewRenders(unittest.TestCase):
    """tools/preview_ui.py is the only way to see this UI without the camera hardware.

    It is not a gate on the APK, but it is worse than useless if it silently stops
    rendering: the layout gets approved on the strength of a page that no longer reflects
    it. So it builds from the same inputs patch_ui uses, and that is asserted here.
    """

    def setUp(self):
        sys.path.insert(0, str(ROOT / "tools"))
        try:
            import preview_ui  # noqa: PLC0415
        except ImportError as exc:                     # pragma: no cover
            self.skipTest(f"preview_ui is not importable: {exc}")
        self.preview_ui = preview_ui

    def test_the_page_builds_from_the_layout_and_the_theme(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        catalog = json.loads(self.preview_ui.CATALOG.read_text(encoding="utf-8"))
        page = self.preview_ui.build_html(theme, patch_ui.layout_for(theme), catalog, None,
                                          patch_ui.DEFAULT_FORK)
        recipe, _group_label, total, pos = self.preview_ui.pick(catalog, None)
        self.assertIn(recipe["name"], page,
                      "the preview does not show the recipe it was told to render")
        self.assertIn(f"{pos} / {total}", page, "the position counter is missing")
        # Not 'no brace at all' — the page carries CSS and a script. Only a {token} that
        # substitution should have filled is a failure.
        self.assertIsNone(re.search(r"\{[a-z_]+\}", page),
                          "an unfilled {token} reached the preview page")

    def test_the_badge_keeps_an_opaque_fill(self):
        """ACTIVE is drawn with white text; only an opaque fill makes it readable.

        It is the one element allowed to break the 'no white on frost' rule, and the
        reason is that fill. If the preview ever loses it, the preview is lying.
        """
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        catalog = json.loads(self.preview_ui.CATALOG.read_text(encoding="utf-8"))
        page = self.preview_ui.build_html(theme, patch_ui.layout_for(theme), catalog, None,
                                          patch_ui.DEFAULT_FORK)
        badge = re.search(r'class="badge" style="([^"]*)"', page)
        self.assertIsNotNone(badge, "the preview lost the ACTIVE badge")
        if patch_ui.DEFAULT_FORK.is_dir():
            self.assertIn("background:", badge.group(1),
                          "the ACTIVE badge has no fill — white text on the frost is "
                          "invisible, and the real one is an opaque green slab")


class TestBundledFont(unittest.TestCase):
    """The rounded face has to be bundled, and bundling it has one silent failure mode.

    API 10 has no rounded system font and no android:fontFamily, so the .ttf ships as a
    raw asset. If the packaging step loses its -A flag the file simply is not in the APK,
    createFromAsset throws, the catch swallows it, and the app renders Droid Sans — a
    failure with no error message anywhere. Everything here guards against that silence.
    """

    def test_the_theme_names_four_files_that_are_actually_there(self):
        """Two Latin faces and two CJK faces — one pair per language.

        The CJK pair is not decoration. These bodies may carry no Chinese system font at
        all, and a missing face does not announce itself: createFromAsset throws, the
        catch swallows it, and every Chinese recipe name renders as tofu — which reads as
        a data bug rather than a missing font.
        """
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        names = patch_ui.fonts_for(theme)          # raises on a name with no file
        self.assertEqual(4, len(names))
        for name in names:
            path = patch_ui.FONT_DIR / name
            self.assertTrue(path.is_file(), f"assets/fonts/{name} is missing")
            self.assertTrue(name.endswith(".ttf"), f"{name} is not a .ttf")
            # sfnt magic: 0x00010000 for TrueType outlines, 'OTTO' for CFF. A file that is
            # neither is an HTML error page saved under a .ttf name, which happens more
            # often than it should when a font is fetched by URL.
            self.assertIn(path.read_bytes()[:4], (b"\x00\x01\x00\x00", b"OTTO"),
                          f"assets/fonts/{name} is not a font")

    def test_the_licence_travels_with_the_font(self):
        """The OFL's one condition, and the one failure nothing else here can see.

        NOTICE.md requires the licence obligation to travel with the APK rather than stay
        behind in the repository. A payload that quietly dropped the .txt would still
        build, still look right on the camera, and still pass every other case in this
        class — a missing text file cannot make the app misbehave. So the payload set is
        asserted directly instead of trusting the copy loop to keep including it.
        """
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        payloads = patch_ui.font_payloads(theme)
        for name in patch_ui.fonts_for(theme):
            self.assertIn(name, payloads, f"{name} would not be copied into the checkout")
        licences = [n for n in payloads if n.lower().endswith(".txt")]
        self.assertTrue(licences,
                        "no licence text in the font payload: the OFL requires the licence "
                        "to ship with the font it covers, and NOTICE.md says so explicitly")
        text = payloads[licences[0]].decode("utf-8", "replace").upper()
        self.assertIn("SIL OPEN FONT LICENSE", text,
                      f"{licences[0]} does not read like the OFL")

    def test_a_font_the_theme_invents_is_rejected(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        with self.assertRaises(SystemExit, msg="a missing .ttf must stop the build here, "
                                               "not at launch on the camera"):
            patch_ui.fonts_for(dict(theme, font_bold="NotARealFace.ttf"))

    def test_the_packaging_step_ships_assets(self):
        fork = ROOT / "build" / "recipe-lab-sony-pmca"
        if not (fork / "AndroidManifest.xml").is_file():
            self.skipTest("no upstream checkout — nothing to compare the anchors against")
        for rel, old, new, label in patch_ui.script_edits():
            path = fork / rel
            self.assertTrue(path.is_file(), f"{rel} is gone from the checkout")
            text = path.read_text(encoding="utf-8")
            self.assertTrue(old in text or new in text,
                            f"{rel}: the aapt line moved — {label} must be re-anchored")
        # Upstream keeps build.sh and build.cmd in step by its own rule; a patch that only
        # lands in one of them makes Linux and Windows builds disagree, and CI is Linux.
        flags = [("-A assets" in (fork / rel).read_text(encoding="utf-8"))
                 for rel, _o, _n, _l in patch_ui.script_edits()]
        self.assertTrue(all(flags) or not any(flags),
                        "only one of build.sh / build.cmd carries -A assets")


class TestAnchorsMatchUpstream(unittest.TestCase):
    """Silent drift detector — skipped loudly when there is no checkout to check."""

    def setUp(self):
        self.fork = ROOT / "build" / "recipe-lab-sony-pmca"
        if not (self.fork / "AndroidManifest.xml").is_file():
            self.skipTest("no upstream checkout — nothing to compare the anchors against")

    def test_every_java_anchor_still_resolves(self):
        """Each anchor must still match the upstream line, or already be applied.

        After patch_ui has run, the OLD string is gone and the NEW one is there — both are
        fine. What fails is neither: the pack or upstream moved that code and every future
        build would silently skip the edit, shipping an APK that quietly lost its theme.
        """
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        for fname, old, new, label in patch_ui.anchors(theme):
            text = patch_ui.find_source(self.fork, fname).read_text(encoding="utf-8")
            self.assertTrue(
                old in text or new in text,
                f"{fname}: {label!r} matches neither the upstream line nor the patched one — "
                "upstream moved that code, so update the anchor in tools/patch_ui.py",
            )


class TestEditorKeyAxes(unittest.TestCase):
    """The FN editor's two axes: UP/DOWN walk the list, LEFT/RIGHT dial the value.

    v0.90/0.91 shipped the opposite mapping — LEFT/RIGHT walked the rows, UP/DOWN dialled
    the value — on the theory that the editor should agree with the horizontal chip strip it
    replaced. On hardware (α7S II, v0.91 feedback) that reads backwards: the editor is a
    VERTICAL list, and a list is walked with its own axis. v0.92 swaps the two, and pins the
    wheel and the dial to stepValue inside the editor as well — the wheel previously fell
    through to nextRecipe there and silently changed the recipe mid-edit.
    """

    def setUp(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        self.edits = {label: new for _f, _o, new, label in patch_ui.anchors(theme)}

    def _new(self, label):
        self.assertIn(label, self.edits,
                      f"tools/patch_ui.py has no anchor labelled {label!r} — the editor "
                      "key map was edited away instead of fixed")
        return self.edits[label]

    def test_up_down_walks_the_list_in_the_editor(self):
        new = self._new("editor: up/down walks the list")
        self.assertIn("if (bottomOnly) moveEditorRow(e.getScanCode() == K_UP ? -1 : +1);", new,
                      "UP must move the selection UP the list before focus can claim the "
                      "key — the editor is a vertical list now. v1.0.0: it walks via "
                      "moveEditorRow so the cursor lands on PE-overridden (disabled) rows too")
        self.assertIn("else if (focus) stepValue(", new,
                      "the main screen's focused UP/DOWN must keep dialling the value")
        self.assertIn("else toggleLine();", new,
                      "the main screen's UP/DOWN (recipe line ↔ chip strip) must survive")

    def test_saving_hides_the_editor(self):
        """v1.0.0 bug: after storing from the editor, the settings panel stayed on screen.

        The EditorView is a SIBLING of panel/picker, not a child of panel, so
        panel.setVisibility(GONE) does NOT hide it. render() only set editor visibility
        inside the `overlay == 0` branch, which the store path skips (it returns to overlay
        3). So the editor stayed painted over the recipe list. The fix sets editor visibility
        from bottomOnly ahead of the overlay branches, so it is correct on every overlay —
        including the one the store returns to. This test pins that the line lives BEFORE the
        `if (overlay == 3)` early-return in render(), so it actually runs on the store path."""
        fork = ROOT / "build" / "recipe-lab-sony-pmca"
        if not (fork / "AndroidManifest.xml").is_file():
            self.skipTest("no upstream checkout — nothing to compare the anchors against")
        text = patch_ui.find_source(fork, "MainActivity.java").read_text(encoding="utf-8")
        vis_line = "editor.setVisibility(bottomOnly ? View.VISIBLE : View.GONE);"
        self.assertIn(vis_line, text, "render() no longer controls the editor's visibility")
        i_vis = text.index(vis_line)
        i_guard = text.index("picker.setSelected(recipe, browserCol); return;")
        self.assertLess(i_vis, i_guard,
                        "the editor-visibility line sits AFTER the `if (overlay == 3)` "
                        "early-return, so it never runs on the store-return path (overlay 3) "
                        "— the editor would stay painted over the recipe list again")

    def test_left_right_dials_the_value_in_the_editor(self):
        new = self._new("editor: left/right dials the value")
        self.assertIn("if (bottomOnly) stepValue(dir);", new,
                      "LEFT/RIGHT must dial the selected row's value — the walk moved to "
                      "UP/DOWN in v0.92")
        self.assertIn("else if (focus) stepValue(dir);", new,
                      "the main screen's focused LEFT/RIGHT must keep dialling the value")
        self.assertIn("else moveChip(dir);", new,
                      "the main screen's unfocused LEFT/RIGHT must keep walking the strip")
        # The anchor is pinned to the LEFT/RIGHT arm by its own dir line (K_RIGHT). The
        # dial carries an identical body, so a shorter OLD would rewrite the dial's arm too.
        self.assertIn("int dir = e.getScanCode() == K_RIGHT ? +1 : -1;", new)
        self.assertNotIn("K_DIAL_CW", new,
                         "the LEFT/RIGHT anchor leaked into the dial's arm — keep the dir "
                         "line in OLD so the two identical bodies stay distinct")

    def test_the_wheel_and_the_dial_dial_in_the_editor(self):
        wheel = self._new("editor: wheel dials the value")
        dial = self._new("editor: dial dials the value")
        self.assertIn("if (bottomOnly || focus) stepValue(dir);", wheel,
                      "the wheel must dial the selected value in the editor — in v0.91 it "
                      "fell through to nextRecipe and changed the recipe mid-edit")
        self.assertIn("else nextRecipe(dir);", wheel,
                      "outside the editor the wheel still scrolls recipes")
        self.assertIn("if (bottomOnly || focus) stepValue(dir);", dial,
                      "the dial must dial the selected value in the editor")
        self.assertIn("else moveChip(dir);", dial,
                      "outside the editor the unfocused dial still walks the strip")

    def test_the_edit_legend_names_both_axes(self):
        icons = self._new("hint-bar edit icons")
        legend = self._new("hint-bar legend")
        self.assertIn("Legend.LEFTRIGHT", icons, "the legend has no entry for the key that walks")
        self.assertIn("Legend.UPDOWN", icons, "the legend has no entry for the key that dials")
        self.assertIn('{ "param", "value", "done", "done" }', legend)
        self.assertIn('{ "参数", "数值", "完成", "完成" }', legend)
        self.assertEqual(icons.count("Legend."), 4,
                         "the EDIT row must list four icons — Legend pairs icon i with label "
                         "i, so a row of three labels against four icons mislabels every key")


class TestPickerBrowser(unittest.TestCase):
    """The FN browser is replayed whole from assets/ui/PickerView.java, like the layout.

    It is upstream code (not patched line-by-line), so the only thing guarding it is this
    test plus the apply step in tools/patch_ui.py: a checkout builds with whatever
    PickerView.java upstream shipped unless the replay writes ours over it. The old panel was
    a black two-column BRAND|recipes browser; the new one is a single white column.
    """

    def test_picker_template_exists(self):
        self.assertTrue(patch_ui.PICKER_TEMPLATE.is_file(),
                        "assets/ui/PickerView.java (the new single-column browser) is missing")

    def test_picker_replaces_the_black_two_column_panel(self):
        raw = patch_ui.PICKER_TEMPLATE.read_text(encoding="utf-8")
        # The old panel was black (0xF0101010) with a left BRAND column; both must be gone.
        self.assertNotIn("0xF0101010", raw, "the picker still paints the old black panel")
        self.assertNotIn('"BRAND"', raw, "the picker still draws the left BRAND column")
        self.assertNotIn("colX", raw, "the picker still splits into a brand column + content")

    def test_picker_is_white_and_single_column(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        text = patch_ui.picker_for(theme, patch_ui.BASE_PACKAGE)
        # White background comes from frost_top_start, not the old black literal.
        self.assertIn(patch_ui.java_literal(theme["frost_top_start"]), text)
        self.assertNotIn("0xF0101010", text)

    def test_picker_fills_the_package_token_per_target(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        base = patch_ui.picker_for(theme, patch_ui.BASE_PACKAGE)
        self.assertNotIn(patch_ui.PKG_TOKEN, base)
        self.assertIn("package com.hairuoliu.sonysoocrecipes;", base)
        leica = patch_ui.picker_for(theme, "com.hairuoliu.sonysoocrecipes.leica")
        self.assertNotIn(patch_ui.PKG_TOKEN, leica)
        self.assertIn("package com.hairuoliu.sonysoocrecipes.leica;", leica)
        self.assertNotIn("com.hairuoliu.sonysoocrecipes.HintBar", leica)

    def test_picker_has_no_unfilled_token(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        for pkg in (patch_ui.BASE_PACKAGE, "com.hairuoliu.sonysoocrecipes.leica"):
            text = patch_ui.picker_for(theme, pkg)
            leftover = [t for t in patch_ui.PICKER_TOKENS if t in text]
            self.assertEqual([], leftover, f"unfilled token(s) {leftover} in the picker for {pkg}")

    def test_picker_braces_balance(self):
        raw = patch_ui.PICKER_TEMPLATE.read_text(encoding="utf-8")
        self.assertEqual(raw.count("{"), raw.count("}"),
                         "PickerView.java has unbalanced braces — it would not compile")

    def test_picker_font_is_the_approved_nine_thirteen_ten(self):
        """The FN browser font is pinned at 9sp / 13sp / 10sp.

        History: it was bumped to 11/15/12 on request, and every visual defect reported since
        (text running under the PE tag, text escaping the gold selection bar, a tag that no
        longer lined up with the two text lines) traced back to that bump. The bumps were
        reverted and the layout fixes kept — 9/13/10 is now the signed-off baseline, and this
        locks it so a later edit cannot silently grow it again.

        Careful: 13*d / 10*d also appear as vertical baselines in onDraw, so only assert on
        the setTextSize declarations.
        """
        raw = patch_ui.PICKER_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn("head.setTextSize(9 * d)", raw, "header font should be 9*d")
        self.assertIn("item.setTextSize(13 * d)", raw, "recipe-name font should be 13*d")
        self.assertIn("small.setTextSize(10 * d)", raw, "summary font should be 10*d")
        self.assertNotIn("head.setTextSize(11 * d)", raw, "the +2 bump is back on the header")
        self.assertNotIn("item.setTextSize(15 * d)", raw, "the +2 bump is back on the name")
        self.assertNotIn("small.setTextSize(12 * d)", raw, "the +2 bump is back on the summary")

    def test_picker_text_stays_clear_of_the_tag(self):
        """Long recipe names must not run under the PE/CS tag, and the tag must be centred
        between the name and sub-text lines (see the font-bump feedback).

        The name/sub-text are clipped to the left of the tag column, and the tag rect is
        drawn at y+12d..y+24d (between the name baseline y+13d and sub baseline y+24d),
        not at the old top-aligned y+4d..y+16d.
        """
        raw = patch_ui.PICKER_TEMPLATE.read_text(encoding="utf-8")
        # v0.88: the selected row grew a "设置" chip to the LEFT of the tag, so the clip has
        # to stop before that chip as well — otherwise a long name runs under it, which is
        # exactly the defect this test was written for, one column over.
        self.assertIn("c.clipRect(x - 4 * d, y, on ? sx - 6 * d : tx - 6 * d, y + rowH)", raw,
                      "recipe text is not clipped clear of the tag column (and of the "
                      "settings chip on the selected row)")
        self.assertIn("r.set(tx, y + 12 * d, tx + tw, y + 24 * d)", raw,
                      "the PE/CS tag is not centred between the two text lines")
        self.assertNotIn("y + 4 * d, tx + tw, y + 16 * d", raw,
                         "the tag is still top-aligned with the name line")
        # v0.89: the widths are measured once in the constructor now (there are exactly three
        # possible strings) instead of twice per row per frame — same geometry, far less work
        # while the dial is spinning.
        self.assertIn("tagW = Math.max(head.measureText(", raw,
                      "the PE/CS tag width is no longer cached in the constructor")
        self.assertIn("+ 16 * d, 52 * d", raw,
                      "the PE/CS tag must stay a wider pill (16d padding, 52d floor), "
                      "not the old tight box")

    def test_each_brand_starts_with_a_divider(self):
        """v0.89: scrolling past a brand boundary has to be visible, not just readable.

        The list used to draw the brand name on its own with no separator, so on a long
        scroll the boundary between two brands looked like one more recipe row. The divider
        is drawn at the top of every brand header row, except when that row is the first
        thing in the viewport (a line with nothing above it reads as an artefact).
        """
        raw = patch_ui.PICKER_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn("c.drawLine(pad, y + d, w - pad, y + d, rule)", raw,
                      "brand headers have no divider above them")
        # v0.91: the brand name is now as big as the recipe names (item paint, not head), and
        # the count moved to the far right of the row — it is metadata, not part of the label.
        self.assertIn("c.drawText(Recipes.GROUPS[gg].toUpperCase(), x, y + 17 * d, item)", raw,
                      "the brand header no longer names the brand at the recipe size")
        self.assertIn("String cnt = String.valueOf(count);", raw,
                      "the group count is no longer drawn at the right edge")
        self.assertIn("c.drawText(cnt, xr - small.measureText(cnt), y + 17 * d, small)", raw,
                      "the group count is not right-aligned on its own row")
        self.assertIn("if (count == 0) continue;", raw,
                      "an empty group must not draw a header (a whitelist pack can leave one)")

    def test_the_picker_binds_the_bundled_face(self):
        """v0.89: a canvas-drawn view does NOT inherit the bundled font.

        MainActivity.applyFont() binds the face to TextViews and to Legend.FONT. Canvas views
        build their own Paints and have to be told - which is why the browser list rendered
        安布罗式湿版 and 宝丽来 Type 100 褐调 as boxes while the main screen was fine.
        """
        raw = patch_ui.PICKER_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn("public static Typeface FONT;", raw,
                      "PickerView has no font hook — applyFont() cannot reach it")
        self.assertIn("head.setTypeface(FONT); item.setTypeface(FONT); small.setTypeface(FONT);",
                      raw, "the picker's Paints never receive the bundled face")

    def test_the_selected_row_carries_a_settings_affordance(self):
        """v0.88: the browser row has to show something that reads as a button.

        "FN 之后界面上没有设置按钮" — the row drew a name and a PE/CS tag and nothing else,
        so ENTER (which only closed the list and popped a toast) looked exactly like the
        previous release. The chip is drawn on the SELECTED row only and sits left of the
        tag; the footer legend has to say what ENTER/RIGHT now do, or the chip is a button
        with no label.
        """
        raw = patch_ui.PICKER_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn('String set = Recipes.ZH ? "设置" : "SET";', raw,
                      "the selected row has no settings chip")
        self.assertIn("float sx = tx - 8 * d - sw;", raw,
                      "the settings chip is not placed left of the tag column")
        self.assertIn("c.drawText(set, sx + 8 * d, y + 21 * d, head)", raw,
                      "the settings chip is not drawn on the same line as the tag")
        self.assertIn('TEXT_ZH = { "移动", "设置", "关闭" }', raw,
                      "the key legend still calls ENTER '选择' — it opens the editor now")

    def test_the_selection_bar_covers_the_enlarged_text(self):
        """The gold selection bar must actually cover the row's text.

        The +2 font bump made this fail silently: name baseline y+13d (15d font) and
        sub-text baseline y+24d (12d font) put the sub-text descenders at ~y+27d, while the
        bar stopped at y+rowH-5d (== y+25d) — so it cut through the bottom of the text.
        rowH is 30d, hence the bottom must reach at least rowH-2d.
        """
        raw = patch_ui.PICKER_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn("r.set(x - 6 * d, y + d / 2, xr + 6 * d, y + rowH - 2 * d)", raw,
                      "the selection bar does not extend far enough to cover the sub-text")
        self.assertNotIn("y + rowH - 5 * d", raw,
                         "the selection bar still stops above the sub-text descenders")
        self.assertNotIn("y - 4 * d, xr + 6 * d", raw,
                         "the bar sheets empty gold well above the name glyphs again")

    def test_the_header_has_room_above_its_divider(self):
        """'RECIPES · N' must not sit on top of the divider line below it.

        The baseline is at pad+7d and the divider at top-5d. With top = pad+16d the two were
        only ~2d apart below the descenders, which read as the title sitting on the rule.
        """
        raw = patch_ui.PICKER_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn("float top = pad + 20 * d, bottom = h - pad - 24 * d;", raw,
                      "the header band no longer reserves room above the divider")
        self.assertIn("c.drawLine(pad, top - 5 * d, w - pad, top - 5 * d, rule);", raw,
                      "the divider moved; re-check its clearance from the header baseline")


class TestEditorView(unittest.TestCase):
    """v0.91: the settings editor is now a vertical list (EditorView), not the chip strip.

    It replaces the horizontal chip strip as the editor surface, and it is the one place the
    "settings got smaller / percentage disappeared" report could be answered — because the
    old strip hid STYLE/SAT/CON/SHARP/MTX/STRENGTH under a Picture Effect, and a horizontal
    strip showed two chips at a time, both of which read as "fewer controls". The editor
    lists every parameter, label left and value right, greying the ones a Picture Effect
    overrides instead of hiding them. It is a tracked template replayed whole, like the
    picker, so it needs the same two guards: no unfilled token, and balanced braces.
    """

    def test_editor_template_exists(self):
        self.assertTrue(patch_ui.EDITOR_TEMPLATE.is_file(),
                        "assets/ui/EditorView.java (the vertical editor) is missing")

    def test_editor_fills_the_package_token_per_target(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        base = patch_ui.editor_for(theme, patch_ui.BASE_PACKAGE)
        self.assertNotIn(patch_ui.PKG_TOKEN, base)
        self.assertIn("package com.hairuoliu.sonysoocrecipes;", base)
        leica = patch_ui.editor_for(theme, "com.hairuoliu.sonysoocrecipes.leica")
        self.assertNotIn(patch_ui.PKG_TOKEN, leica)
        self.assertIn("package com.hairuoliu.sonysoocrecipes.leica;", leica)

    def test_editor_has_no_unfilled_token(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        for pkg in (patch_ui.BASE_PACKAGE, "com.hairuoliu.sonysoocrecipes.leica"):
            text = patch_ui.editor_for(theme, pkg)
            leftover = [t for t in patch_ui.EDITOR_TOKENS if t in text]
            self.assertEqual([], leftover, f"unfilled token(s) {leftover} for {pkg}")

    def test_editor_braces_balance(self):
        raw = patch_ui.EDITOR_TEMPLATE.read_text(encoding="utf-8")
        self.assertEqual(raw.count("{"), raw.count("}"),
                         "EditorView.java has unbalanced braces — it would not compile")

    def test_editor_lists_every_row_and_greys_disabled_ones(self):
        """The editor must carry the disabled-rows affordance, or a Picture Effect recipe
        looks like it lost half its controls again. v1.0.0: the note is the user's wording
        （不能改动） and rides the value string itself — MainActivity appends it to the value
        so it reads "标准（不能改动）" on one line, instead of a second line under the value
        (which read as noise on hardware). The template still reads the disabled flag to grey
        the row out; it no longer draws its own second-line note."""
        raw = patch_ui.EDITOR_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn("boolean disabled = off != null && off[i];", raw,
                      "the editor does not read the disabled flag for each row")
        # the （不能改动） note now comes from MainActivity, not a second line in the template
        self.assertNotIn('c.drawText(Recipes.ZH ? "（不能改动）" : "(read-only)", xr, y + 24 * d, note);',
                         raw,
                         "the editor still draws the read-only note on its own second line — "
                         "MainActivity should append it to the value instead")
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        appended = [n for _f, _o, n, label in patch_ui.anchors(theme)
                    if label == "editor: read-only note rides the value"]
        self.assertEqual(len(appended), 1, "the read-only-note anchor is missing or duplicated")
        self.assertIn('(Recipes.ZH ? "（不能改动）" : " (read-only)")', appended[0],
                      "MainActivity does not append the （不能改动） note to the value string")

    def test_editor_values_end_at_the_right_edge(self):
        """v0.91 hardware report: the right side showed nothing. The value was drawn
        left-aligned FROM xr, so every glyph started at the clip's right boundary and fell
        outside it — Paint's default alignment is LEFT. The value must be right-aligned so
        it ends at xr, and the alignment must be restored afterwards or the label paint
        would draw right-aligned on the next row."""
        raw = patch_ui.EDITOR_TEMPLATE.read_text(encoding="utf-8")
        i_align = raw.find("item.setTextAlign(Paint.Align.RIGHT);")
        i_draw = raw.find("c.drawText(values[i], xr,")
        self.assertGreaterEqual(i_align, 0,
                                "the value is not right-aligned — it will draw outside its clip")
        self.assertGreater(i_draw, i_align,
                           "the value is drawn before the alignment is set — it renders "
                           "left-aligned from xr and vanishes past the clip edge again")
        i_restore = raw.find("item.setTextAlign(Paint.Align.LEFT);", i_draw)
        self.assertGreater(i_restore, i_draw,
                           "the RIGHT alignment is never restored — the next label would "
                           "draw right-aligned out of its own clip")

    def test_editor_rows_stay_inside_the_middle_box(self):
        """v0.91 hardware report: a half-scrolled row painted over the header title
        ("选中的菜单和左上角的名字重合"). The row loop's bounds check only skips rows that
        are FULLY outside [listTop, listBottom], so a straddling row drew across the
        header's baseline. The whole loop must sit inside a clip to the list region."""
        raw = patch_ui.EDITOR_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn("c.clipRect(0, listTop, w, listBottom);", raw,
                      "the row list is not clipped to the list region — scrolled rows will "
                      "paint over the header title again")
        i_clip = raw.find("c.clipRect(0, listTop, w, listBottom);")
        i_loop = raw.find("for (int i = 0; i < n; i++, y += ROW_H * d)")
        self.assertGreater(i_loop, i_clip,
                           "the row loop starts before the clip — straddling rows escape it")
        self.assertGreater(raw.find("c.restore();", i_loop), i_loop,
                           "the clip is never popped — everything after the list would be "
                           "clipped away, legend included")

    def test_editor_legend_names_updown_first(self):
        """v0.92: UP/DOWN walk the list, so the legend's first glyph pair must be the
        vertical arrows. Swapping the anchors without swapping the legend would label the
        keys with each other's job."""
        raw = patch_ui.EDITOR_TEMPLATE.read_text(encoding="utf-8")
        self.assertIn("ICONS = { Legend.UPDOWN, Legend.LEFTRIGHT, Legend.ENTER, Legend.MENU };",
                      raw,
                      "the editor legend still leads with LEFT/RIGHT — it must lead with "
                      "UP/DOWN after the v0.92 axis swap")


class TestPreviewPickerRenders(unittest.TestCase):
    """tools/preview_picker.py is the only way to see the FN browser without the camera.

    The browser is Canvas-drawn, so the layout-aware preview_ui cannot reach it; this tool
    mirrors PickerView.onDraw() from the catalog and theme. Like TestPreviewRenders, it is
    not a gate on the APK, but it is useless if it silently stops reflecting the browser.
    """

    def setUp(self):
        sys.path.insert(0, str(ROOT / "tools"))
        try:
            import preview_picker  # noqa: PLC0415
        except ImportError as exc:                     # pragma: no cover
            self.skipTest(f"preview_picker is not importable: {exc}")
        self.preview_picker = preview_picker

    def test_the_page_builds_from_the_catalog_and_theme(self):
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        catalog = json.loads(self.preview_picker.CATALOG.read_text(encoding="utf-8"))
        selected = self.preview_picker.pick_selected(catalog, None)
        page = self.preview_picker.build_html(theme, catalog, 2, selected, "Quicksand")
        self.assertIn("RECIPES", page, "the preview does not show the browser header")
        # both the current and the bumped frame are on the page
        self.assertIn("Current (9 / 13 / 10 sp)", page)
        self.assertIn("After (+2:", page)
        # the window must actually render recipe rows, not a blank panel (the scroll
        # anchor bug drew the selection off-screen and showed nothing)
        self.assertIn("rgba(242,184,92", page,
                      "no selection highlight drawn — the browser window rendered blank")
        self.assertIsNone(re.search(r"\{[a-z_]+\}", page),
                          "an unfilled {token} reached the preview page")

    def test_the_bump_changes_the_rendered_font_size(self):
        """The bumped frame must actually draw larger text than the current one.

        A bump that changed nothing would make the preview a lie; this checks the two
        frames disagree on the rendered name font.
        """
        theme = patch_ui.load_theme(patch_ui.DEFAULT_THEME)
        catalog = json.loads(self.preview_picker.CATALOG.read_text(encoding="utf-8"))
        selected = self.preview_picker.pick_selected(catalog, None)
        before = self.preview_picker.render_frame(theme, catalog, 0, selected, "Quicksand")
        after = self.preview_picker.render_frame(theme, catalog, 2, selected, "Quicksand")
        self.assertNotEqual(before, after, "the bumped frame is identical to the current one")


class TestPreviewMirrorsTheBrowser(unittest.TestCase):
    """preview_picker.py and PickerView.java state the same layout numbers twice.

    The preview exists so the browser can be judged in pixels without the camera. That
    promise only holds while its copy of the geometry is the copy that ships. Every defect
    fixed over the last rounds — text running under the PE/CS tag, text escaping the gold
    selection bar, the header sitting on its own divider — was found by eye against this
    preview, so any silent divergence means the next round is judged against a layout the
    camera will never draw.

    Nothing here restates a number. Each one is pulled out of both files and compared, so a
    change on either side is either mirrored on the other or a failure with the two values
    named in the message.
    """

    # One entry per shared value: how each side spells the *same* thing.
    JAVA_SIDE = {
        "pad":            r"pad\s*=\s*([\d.]+)\s*\*\s*d",
        "header reserve": r"top\s*=\s*pad\s*\+\s*([\d.]+)\s*\*\s*d",
        "footer reserve": r"bottom\s*=\s*h\s*-\s*pad\s*-\s*([\d.]+)\s*\*\s*d",
        "row height":     r"rowH\s*=\s*([\d.]+)\s*\*\s*d",
        "header size":    r"head\.setTextSize\(\s*([\d.]+)\s*\*\s*d\s*\)",
        "name size":      r"item\.setTextSize\(\s*([\d.]+)\s*\*\s*d\s*\)",
        "sub-text size":  r"small\.setTextSize\(\s*([\d.]+)\s*\*\s*d\s*\)",
    }
    PYTHON_SIDE = {
        "pad":            r"pad\s*=\s*([\d.]+)\s*\*\s*d",
        "header reserve": r"top\s*=\s*pad\s*\+\s*([\d.]+)\s*\*\s*d",
        "footer reserve": r"bottom\s*=\s*SCREEN_H\s*-\s*pad\s*-\s*([\d.]+)\s*\*\s*d",
        "row height":     r"row_h\s*=\s*([\d.]+)\s*\*\s*d",
        "header size":    r"head_sz\s*=\s*\(\s*([\d.]+)\s*\+\s*bump\s*\)\s*\*\s*d",
        "name size":      r"item_sz\s*=\s*\(\s*([\d.]+)\s*\+\s*bump\s*\)\s*\*\s*d",
        "sub-text size":  r"small_sz\s*=\s*\(\s*([\d.]+)\s*\+\s*bump\s*\)\s*\*\s*d",
    }

    @staticmethod
    def _java() -> str:
        return patch_ui.PICKER_TEMPLATE.read_text(encoding="utf-8")

    @staticmethod
    def _python() -> str:
        return (ROOT / "tools" / "preview_picker.py").read_text(encoding="utf-8")

    def _stated_value(self, source: str, pattern: str, where: str, what: str) -> str:
        found = re.search(pattern, source)
        self.assertIsNotNone(
            found,
            f"{where} no longer declares {what}; the preview can no longer be trusted to "
            f"mirror the browser ({pattern})",
        )
        return found.group(1)

    def test_both_sides_declare_the_same_geometry(self):
        java, python = self._java(), self._python()
        for what in self.JAVA_SIDE:
            ship = self._stated_value(java, self.JAVA_SIDE[what], "PickerView.java", what)
            preview = self._stated_value(python, self.PYTHON_SIDE[what],
                                         "preview_picker.py", what)
            self.assertEqual(
                ship, preview,
                f"{what} diverged: the APK draws {ship} but the preview draws {preview}, so "
                "pixels approved in the preview are not the pixels that ship.",
            )

    def test_the_guarded_geometry_is_still_the_signed_off_sizes(self):
        """9/13/10 sp is the set signed off against the preview; do not drift off it silently.

        The sizes were once bumped to 11/15/12 and every visual defect afterwards traced
        back to that bump. Extracting them (rather than restating them) means this only
        fails when someone actually changes them — which should be a deliberate act.
        """
        java = self._java()
        for what in ("header size", "name size", "sub-text size"):
            self.assertEqual(
                self._stated_value(java, self.JAVA_SIDE[what], "PickerView.java", what),
                {"header size": "9", "name size": "13", "sub-text size": "10"}[what],
                f"{what} moved off the signed-off value; re-review the browser in the preview "
                "before shipping new sizes",
            )


if __name__ == "__main__":
    unittest.main(verbosity=2)
